# Generated by Django 3.2.8 on 2022-01-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('Green', 'bg-success'), ('Red', 'bg-danger'), ('Black', 'bg-dark'), ('Light', 'bg-light'), ('Yellow ', 'bg-warning'), ('Sky Blue ', 'bg-info'), ('Gray ', 'bg-secondary')], default='Black', max_length=32),
        ),
    ]
