# Generated by Django 3.2.8 on 2022-02-14 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='post',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='like',
            field=models.ManyToManyField(related_name='activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
