# Generated by Django 3.2.8 on 2022-01-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('success', 'Green '), ('danger', 'Red'), ('dark', 'Black'), ('light', 'Light'), ('warning', 'Yellow'), ('info', 'Sky Blue'), ('secondary ', 'Grey')], default='Black', max_length=32, verbose_name='Chuse categry color'),
        ),
    ]
