# Generated by Django 3.2.8 on 2022-02-14 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20220214_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='like',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
