# Generated by Django 3.2.8 on 2022-01-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220107_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_on'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
