# Generated by Django 3.2.8 on 2022-02-14 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_activity_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_date'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='like',
        ),
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='app.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='auth.user'),
            preserve_default=False,
        ),
    ]
