# Generated by Django 3.2.8 on 2022-03-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_additional_detail_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_additional_detail',
            name='user_profile',
            field=models.ImageField(upload_to='app/userprofile'),
        ),
    ]
